In [45]:
import numpy as np
import pandas as p
import math
from sklearn.preprocessing import OneHotEncoder

In [3]:
file_path = '../data/m5/sales_train_evaluation.csv'
with open(file_path, 'r') as fin:
    sales_data = pd.read_csv(fin, ',')

In [5]:
for item in sales_data.itertuples():
    print(item[1])
    break

HOBBIES_1_001_CA_1_evaluation


In [33]:
sales_data

id        item_id    dept_id   cat_id  \
0      HOBBIES_1_001_CA_1_evaluation  HOBBIES_1_001  HOBBIES_1  HOBBIES   
1      HOBBIES_1_002_CA_1_evaluation  HOBBIES_1_002  HOBBIES_1  HOBBIES   
2      HOBBIES_1_003_CA_1_evaluation  HOBBIES_1_003  HOBBIES_1  HOBBIES   
3      HOBBIES_1_004_CA_1_evaluation  HOBBIES_1_004  HOBBIES_1  HOBBIES   
4      HOBBIES_1_005_CA_1_evaluation  HOBBIES_1_005  HOBBIES_1  HOBBIES   
...                              ...            ...        ...      ...   
30485    FOODS_3_823_WI_3_evaluation    FOODS_3_823    FOODS_3    FOODS   
30486    FOODS_3_824_WI_3_evaluation    FOODS_3_824    FOODS_3    FOODS   
30487    FOODS_3_825_WI_3_evaluation    FOODS_3_825    FOODS_3    FOODS   
30488    FOODS_3_826_WI_3_evaluation    FOODS_3_826    FOODS_3    FOODS   
30489    FOODS_3_827_WI_3_evaluation    FOODS_3_827    FOODS_3    FOODS   

      store_id state_id  d_1  d_2  d_3  d_4  ...  d_1932  d_1933  d_1934  \
0         CA_1       CA    0    0    0    0  ...       2       4       0   
1         CA_1       CA    0    0    0    0  ...       0       1       2   
2         CA_1       CA    0    0    0    0  ...       1       0       2   
3         CA_1       CA    0    0    0    0  ...       1       1       0   
4         CA_1       CA    0    0    0    0  ...       0       0       0   
...        ...      ...  ...  ...  ...  ...  ...     ...     ...     ...   
30485     WI_3       WI    0    0    2    2  ...       1       0       3   
30486     WI_3       WI    0    0    0    0  ...       0       0       0   
30487     WI_3       WI    0    6    0    2  ...       0       0       1   
30488     WI_3       WI    0    0    0    0  ...       1       1       1   
30489     WI_3       WI    0    0    0    0  ...       1       2       0   

       d_1935  d_1936  d_1937  d_1938  d_1939  d_1940  d_1941  
0           0       0       0       3       3       0       1  
1           1       1       0       0       0       0       0  
2           0       0       0       2       3       0       1  
3           4       0       1       3       0       2       6  
4           2       1       0       0       2       1       0  
...       ...     ...     ...     ...     ...     ...     ...  
30485       0       1       1       0       0       1       1  
30486       0       0       0       1       0       1       0  
30487       2       0       1       0       1       0       2  
30488       4       6       0       1       1       1       0  
30489       5       4       0       2       2       5       1  

[30490 rows x 1947 columns]

In [7]:
features_path = '../data/m5/calendar.csv'
with open(features_path, 'r') as fin:
    features = pd.read_csv(features_path, ',')

In [15]:
np.asarray(features[['wday', 'month', 'snap_CA', 'snap_TX', 'snap_WI']][:1941])

array([[1, 1, 0, 0, 0],
       [2, 1, 0, 0, 0],
       [3, 1, 0, 0, 0],
       ...,
       [7, 5, 0, 0, 0],
       [1, 5, 0, 0, 0],
       [2, 5, 0, 0, 0]])

In [64]:
feats_2 = features['event_type_1'][:1941]
cats = list(feats_2.unique())
cats.remove(np.nan)

feats_2 = [[''] if isinstance(f, float) else [f] for f in feats_2]
enc = OneHotEncoder(categories=[cats,], handle_unknown='ignore', sparse=False)
feats_2 = enc.fit_transform(feats_2)
print(feats_2[:30])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [61]:
features[features['event_type_1'] == 'Cultural']
features.iloc[-30:]

date  wm_yr_wk    weekday  wday  month  year       d  \
1939  2016-05-21     11617   Saturday     1      5  2016  d_1940   
1940  2016-05-22     11617     Sunday     2      5  2016  d_1941   
1941  2016-05-23     11617     Monday     3      5  2016  d_1942   
1942  2016-05-24     11617    Tuesday     4      5  2016  d_1943   
1943  2016-05-25     11617  Wednesday     5      5  2016  d_1944   
1944  2016-05-26     11617   Thursday     6      5  2016  d_1945   
1945  2016-05-27     11617     Friday     7      5  2016  d_1946   
1946  2016-05-28     11618   Saturday     1      5  2016  d_1947   
1947  2016-05-29     11618     Sunday     2      5  2016  d_1948   
1948  2016-05-30     11618     Monday     3      5  2016  d_1949   
1949  2016-05-31     11618    Tuesday     4      5  2016  d_1950   
1950  2016-06-01     11618  Wednesday     5      6  2016  d_1951   
1951  2016-06-02     11618   Thursday     6      6  2016  d_1952   
1952  2016-06-03     11618     Friday     7      6  2016  d_1953   
1953  2016-06-04     11619   Saturday     1      6  2016  d_1954   
1954  2016-06-05     11619     Sunday     2      6  2016  d_1955   
1955  2016-06-06     11619     Monday     3      6  2016  d_1956   
1956  2016-06-07     11619    Tuesday     4      6  2016  d_1957   
1957  2016-06-08     11619  Wednesday     5      6  2016  d_1958   
1958  2016-06-09     11619   Thursday     6      6  2016  d_1959   
1959  2016-06-10     11619     Friday     7      6  2016  d_1960   
1960  2016-06-11     11620   Saturday     1      6  2016  d_1961   
1961  2016-06-12     11620     Sunday     2      6  2016  d_1962   
1962  2016-06-13     11620     Monday     3      6  2016  d_1963   
1963  2016-06-14     11620    Tuesday     4      6  2016  d_1964   
1964  2016-06-15     11620  Wednesday     5      6  2016  d_1965   
1965  2016-06-16     11620   Thursday     6      6  2016  d_1966   
1966  2016-06-17     11620     Friday     7      6  2016  d_1967   
1967  2016-06-18     11621   Saturday     1      6  2016  d_1968   
1968  2016-06-19     11621     Sunday     2      6  2016  d_1969   

        event_name_1 event_type_1  event_name_2 event_type_2  snap_CA  \
1939             NaN          NaN           NaN          NaN        0   
1940             NaN          NaN           NaN          NaN        0   
1941             NaN          NaN           NaN          NaN        0   
1942             NaN          NaN           NaN          NaN        0   
1943             NaN          NaN           NaN          NaN        0   
1944             NaN          NaN           NaN          NaN        0   
1945             NaN          NaN           NaN          NaN        0   
1946             NaN          NaN           NaN          NaN        0   
1947             NaN          NaN           NaN          NaN        0   
1948     MemorialDay     National           NaN          NaN        0   
1949             NaN          NaN           NaN          NaN        0   
1950             NaN          NaN           NaN          NaN        1   
1951  NBAFinalsStart     Sporting           NaN          NaN        1   
1952             NaN          NaN           NaN          NaN        1   
1953             NaN          NaN           NaN          NaN        1   
1954             NaN          NaN           NaN          NaN        1   
1955             NaN          NaN           NaN          NaN        1   
1956  Ramadan starts    Religious           NaN          NaN        1   
1957             NaN          NaN           NaN          NaN        1   
1958             NaN          NaN           NaN          NaN        1   
1959             NaN          NaN           NaN          NaN        1   
1960             NaN          NaN           NaN          NaN        0   
1961             NaN          NaN           NaN          NaN        0   
1962             NaN          NaN           NaN          NaN        0   
1963             NaN          NaN           NaN          NaN        0   
1964 